#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 1000
      min-spare: 30
    uri-encoding: utf-8

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
  mapper-locations:
    - classpath:/mappers/**.xml

#log
logging:
  level:
    '[com.xun]': DEBUG

#spring
spring:
  servlet:
    multipart:
      max-file-size: 1024MB #单个文件最大
      max-request-size: 102400MB #总文件最大
  datasource:
    url: jdbc:mysql:///myblog?serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false

com:
  xun:
    page:
      page-size: 5 #每页条数

#pageHelper
pagehelper:
  helper-dialect: mysql #指定方言为mysql
  reasonable: true #分页查询合理化（当前页>最大页 为最大页 <0 为1）

